development:
  adapter: postgresql
  encoding: unicode
  database: calendar_exp_development
  pool: 5
  username: kellywaters
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: calendar_exp_test
  pool: 5
  username: kellywaters
  password: 